function [ FS_filter1d, FilterBank1d ] = DualTree_FilterBank_freq( N )
%DUALTREE_FILTERBANK_FREQ Frequency Based Filter Banks for Dual Tree CWT.
%
%   Filters are band-limited here. Generated by fchi.m
%Input:
%   N:  length of the frequency based filter.
%
%Output:
%   FS_filter1d:
%       First Stage Frequency Based Filter Banks. Cell array with 2 cells.
%       FS_filter1d{i}: First Stage Frequency Based Filter Bank for Tree i.
%
%   FilterBank1d:
%       Frequency Based Filter Bank for 2 trees. Cell array with 2 cells.
%
%   Author: Chenzhe Diao
%   Date:   July, 2015


flow = freqfilter1d;
f = 0:1/N:(N-1)/N;
f = f*2*pi-pi;
flow.ffilter = ifftshift(fchi(f, -pi/2, pi/2, 189/256, 189/256));

fhigh = flow.fCQF;

% Tree1
FS_filter1d{1} = [flow, fhigh];
FilterBank1d{1} = [flow, fhigh];

% Tree2
I = sqrt(-1);
theta = f + pi; 
c = exp(-I*theta);
filter = c.* flow.ffilter;
flow02 = freqfilter1d;
flow02.ffilter = filter;
fhigh02 = flow02.fCQF;
FS_filter1d{2} = [flow02, fhigh02];

flow2 = freqfilter1d;
dx = 2*pi/N;
theta = linspace(-pi,pi-dx,N);
c = ifftshift(exp(-I*theta/2));
flow2.ffilter = c.*flow.ffilter;
fhigh2 = flow2.fCQF;
FilterBank1d{2} = [flow2, fhigh2];



end
