function [ FS_fb1d ] = DualTree_GenFSFB_freq( N, width, epsilon )
%DUALTREE_GENFSFB_FREQ Generate First Stage Filter Bank for DT-CWT in
%frequency domain. 
%
%This function only generate filter banks for 2 trees (used in 1d only). 
%The lowpass for tree1 is a real bump in freq domain.
%(So it is also real IIR filter in time domain. The highpass generated by
%CQF pair is also real IIR.) The lowpass used in tree2 is a shift of tree1
%lowpass in time domain. So the tree2 filter bank is also real IIR in time
%domain.
%
%   The input is the parameters to construct the bump function.
%
%   Chenzhe
%   Feb, 2016
%


flow = freqfilter1d;
f = 0:1/N:(N-1)/N;
f = f*2*pi-pi;
flow.ffilter = ifftshift(fchi(f, -width, width, epsilon, epsilon));

fhigh = flow.fCQF;

% Tree1
FS_fb1d{1} = [flow, fhigh];

% Tree2
I = sqrt(-1);
theta = f + pi; 
c = exp(-I*theta);
filter = c.* flow.ffilter;
flow02 = freqfilter1d;
flow02.ffilter = filter;
fhigh02 = flow02.fCQF;
FS_fb1d{2} = [flow02, fhigh02];




end

