function [ FilterBank1d ] = DualTree_GenFB_freq( N, width, epsilon )
%DUALTREE_GENFB_FREQ Generate Filter Bank for DT-CWT in frequency domain. 
%
%This function only generate filter banks for 2 trees (used in 1d only). 
%The lowpass for tree1 is a real bump in freq domain.
%(So it is also real IIR filter in time domain. The highpass generated by
%CQF pair is also real IIR.) The lowpass used in tree2 is a half shift of tree1
%lowpass in freq domain. So the tree2 filter bank is also real IIR in time
%domain.
%
%   The input is the parameters to construct the bump function.
%
%   Chenzhe
%   Feb, 2016
%

flow = freqfilter1d;
f = 0:1/N:(N-1)/N;
f = f*2*pi-pi;
flow.ffilter = ifftshift(fchi(f, -width, width, epsilon, epsilon));

fhigh = flow.fCQF;

% Tree1
FilterBank1d{1} = [flow, fhigh];

% Tree2
I = sqrt(-1);
flow2 = freqfilter1d;
dx = 2*pi/N;
theta = linspace(-pi,pi-dx,N);
c = ifftshift(exp(-I*theta/2));
flow2.ffilter = c.*flow.ffilter;
fhigh2 = flow2.fCQF;
FilterBank1d{2} = [flow2, fhigh2];


end

