function [ fb2d ] = GenAngular_FB_freq2D_disk( ker, N )
%GENANGULAR_FB_FREQ2D_DISK Generate Angular Filter Bank in freqfilter2d.
%The filter bank would match the shape of a disk kernel generated by, e.g.:
%   ker = fspecial('disk', 4);
%
%   Since the frequency response of disk kernel is of ripple shape. We
%   would naturally construct angular frequency fb matching its shape.
%
%Input:
%   ker:
%       blur kernel of disk type. 
%   N:
%       freqfilter2d size
%
%   Chenzhe
%   Jun, 2016
%
%

[M1, M2] = size(ker);

if max(M1, M2)<=256
    ker_fullsize = zeros(256);
else
    ker_fullsize = zeros(M1, M2);
end

ker_fullsize(1:M1, 1:M2) = ker;
fker = abs(fft2(ker_fullsize));

fker1d = fker(1,:);
len = length(fker1d)/2;
fker1d = fker1d(1:len);

% find the zeros of fker1d, take their freq as Rl
tmpdiff = fker1d(2:end) - fker1d(1:end-1);  % positive means increase on the right
% only consider the inner point
diffr = tmpdiff(2:end);
diffr = (diffr>0); % increase on the right
diffl = tmpdiff(1:end-1);
diffl = (diffl<=0);    % decrease on the left

tmp = diffr&diffl;
tmp = [false, tmp, false];  % add back 2 boundary points, the length is still len

Rl = 0:len-1;
Rl = Rl/len*pi;
Rl = Rl(tmp);


K = 6;
Lv = 2;

% fb2d = Angular_FilterBank_freq2D_bump( Rl, K, N );
fb2d = Angular_FilterBank_freq2D( Rl, Lv, K, N );





end

