function [ fb2d ] = GenSquare_FB_freq2D_average( ker, Lv, N )
%GENSQUARE_FB_FREQ2D_AVERAGE Generate Square Filter Bank in freqfilter2d.
%The filter bank would match the shape of a average kernel generated by, e.g.:
%   ker = fspecial('average', 7);
%
%   Since the frequency response of average kernel is of square sinc shape. We
%   would naturally construct square frequency fb matching its shape.
%
%Input:
%   ker:
%       blur kernel of average type. 
%   N:
%       freqfilter2d size
%
%   Chenzhe
%   Jun, 2016
%
%

[M1, M2] = size(ker);

if max(M1, M2)<=256
    ker_fullsize = zeros(256);
else
    ker_fullsize = zeros(M1, M2);
end

ker_fullsize(1:M1, 1:M2) = ker;
fker = abs(fft2(ker_fullsize));

fker1d = fker(1,:);
len = length(fker1d)/2;
fker1d = fker1d(1:len);
tmpdiff = fker1d(2:end) - fker1d(1:end-1);  % positive means increase on the right
% only consider the inner point
diffr = tmpdiff(2:end);
diffr = (diffr>0); % increase on the right
diffl = tmpdiff(1:end-1);
diffl = (diffl<=0);    % decrease on the left

tmp = diffr&diffl;
tmp = [false, tmp, false];  % add back 2 boundary points, the length is still len

Rl = 0:len-1;
Rl = Rl/len*pi;
Rl = Rl(tmp);


fb2d = Square_FilterBank_freq2D(Rl, Lv, N);


end

